#!/bin/bash

script=${1}
filename=${2:-dev}

if [ -z $script ] ; then
  echo "please enter a command after ./ops"

elif [ $script == "start" ] ; then
  echo "starting $filename"
  docker-machine ssh j3swarm-manager-1 "docker-compose -f ./$filename.yml up"

elif [ $script == "stop" ] ; then
  echo "stopping $filename"
  docker-machine ssh j3swarm-manager-1 "docker-compose -f ./$filename.yml down"

elif [ $script == "build" ] ; then
  echo "building $filename"
  docker-machine ssh j3swarm-manager-1 "docker-compose -f ./$filename.yml build"

elif [ $script == "ship" ] ; then
  echo "shipping $filename"
  if [ "$filename" == "dev" ] ; then
    echo "Woops! don't try and ship $filename"
    exit
  elif [ $filename == "manager" ] ; then
    docker-machine ssh j3swarm-manager-1 "docker network create --driver overlay proxy"
  fi

  docker-machine ssh j3swarm-manager-1 "docker stack deploy -c $filename.yml"

fi