version: "3.2"

networks:
  default:
    external: false
  proxy:
    external: true

services:

  site:
    build: ./site
    image: quangoinc/quango-docker-traefik
    command: node index.js
    networks:
      - proxy
      - default
    deploy:
      labels:
        - "traefik.docker.backend=site"
        - "traefik.port=3001"
        - "traefik.frontend.rule=PathPrefix:/"
        - "traefik.frontend.rule=Host:traefik.quangostaging.com"
        - "traefik.docker.network=proxy"
        - "traefik.enable=true"