logLevel = "WARN"
defaultEntryPoints = ["http"]
# defaultEntryPoints = ["http", "https"]

[entryPoints]
 [entryPoints.http]
 address = ":80"
 compress = false
   [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "webmaster@qaungoinc.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
onDemand = true

# [[acme.domains]]
#  main = "traefik.quangostaging.com"

# [web]
# address = ":8080"

# [docker]
# domain = "traefik.quangostaging.com"
# watch = true
# swarmmode = true