logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[web]

[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
  [entryPoints.traefik.auth]
    [entryPoints.traefik.auth.basic]
    # get md5 from htpasswd or http://www.htaccesstools.com/htpasswd-generator/
    users = ["admin:$apr1$I.fb7pJ2$L8rG92IlmEfzqWW87gCnM."]

[acme]
  email = "dev@j3ll3.nl"
  storage = "acme.json"
  entryPoint = "https"
  OnHostRule = true

[acme.httpChallenge]
  entryPoint = "http"

[docker]
  domain = "traefik"
  watch = true
  swarmmode = true

[api]
entrypoint="traefik"